### ISSUE TITLE
Mismatched ship icons in Sea View

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#101]
Just noticed at least in this instance, my Steam Frigate has a sloop icon on the bottom left, will post the screenshot and save here so it can be further investigated, but yeah, not sure what's going on here.

Build: Alpha 8
Storyline: Free Play

[-=Player=- Open Sea January 20th, 1683.zip](https://github.com/PiratesAhoy/new-horizons/files/11348775/-.Player.-.Open.Sea.January.20th.1683.zip)

![Screenshot 2023-04-27 190338](https://user-images.githubusercontent.com/4907391/235015488-a37f69b5-c996-4b69-b633-32183a297d89.png)

**Comment by tommy61157** [comment]
Also noticed a frigate with the Xebec icon as well while playing the hornblower storyline:

![Screenshot 2023-04-27 202717](https://user-images.githubusercontent.com/4907391/235032551-cdf0c7c5-38b7-4f6c-903a-766dca7ccc11.png)

This may be a broader issue with ships not using the correct icons in sea view, will warrant further investigation

**Comment by tommy61157** [comment]
Save for the above screenshot

[-=Player=- Open Sea July 10th, 1798.zip](https://github.com/PiratesAhoy/new-horizons/files/11349085/-.Player.-.Open.Sea.July.10th.1798.zip)

**Comment by Hammie** [comment]
https://github.com/PiratesAhoy/new-horizons/commit/0173813163312441cdc82f871d3e70a2165476b0
