### ISSUE TITLE
Sometimes on the character screen, personal gold will read off the same as crew gold if you have no personal gold

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#103]
This has admittedly been a long-standing visual glitch of the build mod, but I want to see if we can solve it. There is a glitch where if you have no personal gold, then on the personal character screen, under your character portrait where it has the gold bag, it will read the exact same as your crew gold. (see first screenshot, second screenshot is to prove I have no personal gold at that time, I will also provide the save for examination purposes should you wish to see it yourself)

Build: Alpha 8
Storyline: Horatio Hornblower

Save:

[-=Player=- Jamaica. Kingston Naval HQ October 4th, 1798.zip](https://github.com/PiratesAhoy/new-horizons/files/11349288/-.Player.-.Jamaica.Kingston.Naval.HQ.October.4th.1798.zip)

Screenshots:

![Screenshot 2023-04-27 212437](https://user-images.githubusercontent.com/4907391/235039739-24853f5f-bdcc-4769-a78a-6e2642958061.png)
![Screenshot 2023-04-27 212501](https://user-images.githubusercontent.com/4907391/235039768-4ada2871-d762-4a3a-bb20-55d35b6f9fac.png)

**Comment by Hammie** [comment]
The way it is programmed in the scripts, it looks like intentional behavior.
