### ISSUE TITLE
During the Fire Ship quest in Horatio Hornblower, there are no fire effects when you get on the fire ship

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#105]
I will provide a save for you to see, but there is no fire visual particle effects on the ship making it very hard since you normally have to dodge the fire to save the other officer, makes the quest unnecessarily difficult and is ultimately a bug. There should be growing fire particle effects as the scene goes on.

Build: Alpha 8
Storyline: Horatio Hornblower

[-=Player=- Jamaica. Fire Ship deck October 4th, 1798.zip](https://github.com/PiratesAhoy/new-horizons/files/11349357/-.Player.-.Jamaica.Fire.Ship.deck.October.4th.1798.zip)

**Comment by tommy61157** [comment]
The trick if you want to try is to go down the stairs on the left when you hear the scream and then keep going straight remaining left of the mast in the center of the ship, then go around the mast in a sort of u turn which goes to the right and takes you to the officer without being hurt. With fire effects, you would easily be able to see this path, I only know it because I've played this quest so long I literally have memorized it, but the fire effects are needed for newcomers, on second thought, I will apply the questline breaking label since new players will likely keep dying not knowing why

**Comment by tommy61157** [comment]
Issue still persistent in Alpha 13, and I have a more recent save here since I know that the saves may be incompatible at this point: 
[-=Hornblower Test=- Jamaica. Fire Ship deck July 26th, 1798.zip](https://github.com/PiratesAhoy/new-horizons/files/12570920/-.Hornblower.Test.-.Jamaica.Fire.Ship.deck.July.26th.1798.zip)

**Comment by Hammie** [comment]
It does not look like this?

![Beyond New Horizons 9_12_2023 7_38_05 PM](https://github.com/PiratesAhoy/new-horizons/assets/1293169/d0900f71-521a-4bea-8a01-2c6fe209c464)

**Comment by tommy61157** [comment]
This is weird, that appears when I load it from that save I originally provided, however, when loaded from an earlier save and I follow the soldiers and talk to the person at port and then go to the ship, the effects won't appear, so the only way to get the effects to appear is to save on the ship and reload the game, here's the save where you follow the soldiers, go to the port/dock and talk to the person to go to the ship to get it to trigger the version with no effects, I'll include that save along with the respective logs for when it is not working.

[Logs.zip](https://github.com/PiratesAhoy/new-horizons/files/12591553/Logs.zip)

[-=Hornblower Test=- Jamaica. Kingston. Center. July 26th, 1798 1.zip](https://github.com/PiratesAhoy/new-horizons/files/12591554/-.Hornblower.Test.-.Jamaica.Kingston.Center.July.26th.1798.1.zip)

![image](https://github.com/PiratesAhoy/new-horizons/assets/4907391/e225218b-036a-49f1-99b5-fe89fcab973d)

**Comment by Hammie** [comment]
![Beyond New Horizons 9_13_2023 10_06_57 PM](https://github.com/PiratesAhoy/new-horizons/assets/1293169/a7b1a6cb-b1ac-4935-a460-ea5f665fe0bd)
![Beyond New Horizons 9_13_2023 10_07_17 PM](https://github.com/PiratesAhoy/new-horizons/assets/1293169/8f01ada3-3569-46fa-9ab6-5c70a3549cee)
