### ISSUE TITLE
Successfully getting off the fireship along with other points in the following scripted sequence tends to result in a crash.

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#106]
In the save I provide, talk to the guy in front of you, and when you do and go through his dialog, instead of taking you to port, the game will crash, I will provide the save along with the crash dumps. It seems to have a chance to randomly crash at various points in the next long scripted sequence and takes multiple attempts to fully go through it, I will label it as potentially story breaking since it is impossible to get through this without a crash for me it would seem, the save and dumps will be provided, may attach more dumps later as I attempt this more.

[3c19a3b0-476c-455c-8765-e23f8cb5e261.zip](https://github.com/PiratesAhoy/new-horizons/files/11349398/3c19a3b0-476c-455c-8765-e23f8cb5e261.zip)

Build: Alpha 8
Storyline: Horatio Hornblower

**Comment by tommy61157** [comment]
Add the labels you see fit, I just wanted to make sure crash and storyline breaking are on here

**Comment by tommy61157** [comment]
Managed to get through the next scripted sequence completely after a third try, but I would definitely like those crash logs to be looked at and I will still keep the storyline breaking tag on here as someone may get frustrated enough to not keep trying if this crashes enough for them, but I managed to persist in order to get through, testing on the storyline will resume.

**Comment by Hammie** [comment]
Crashlogs indicate the same problem as #91

**Comment by tommy61157** [comment]
Gotcha, thanks, we'll just be sure to close this out once the storm engine issue regarding this is resolved
