### ISSUE TITLE
Loyalty Quest in the Hornblower storyline crashes when recruiting members at the tavern

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#120]
I can consistently get this crash to replicate, at the part in loyalty where you go into the tavern to recruit the new people, the game seems to consistently crash after about 30-45 seconds. I will provide a save right outside the tavern, all you have to do is go into the tavern, have the dialog cycle like normal and it will guarantee a crash if you wait for just a minute. This is in the hornblower storyline on the Alpha 13 build.

[-=Hornblower Test=- Barbados. Bridgetown January 1st, 1799 2.zip](https://github.com/PiratesAhoy/new-horizons/files/12571515/-.Hornblower.Test.-.Barbados.Bridgetown.January.1st.1799.2.zip)

**Comment by Hammie** [comment]
It did not crash for me, but I did have another fader bug.

**Comment by tommy61157** [comment]
Okay weird, I swear it was crashing earlier,

**Comment by tommy61157** [comment]
Oops, didn't mean to close, but yeah, now it is just giving me the fader bug, this fader bug unfortunately is not skippable though through my normal methods since Mrs. Mason becomes unresponsive in response to this one and she is needed for a quest trigger, won't be able to test this further until I have all the fader bug fixes, but yeah, fix the fader bug and this should all continue to work properly
