### ISSUE TITLE
Crash due to empty dialog window

### ISSUE THREAD

**Issue by Hammie** [PiratesAhoy/new-horizons#126]
Game crashes after seeing an empty dialog window.

Storyline: Woodes Rogers
Version: 15.0.0-alpha.14

[-=Test=- Jamaica.zip](https://github.com/PiratesAhoy/new-horizons/files/12641458/-.Test.-.Jamaica.zip)

**Comment by DH2706** [comment]
[-=Player=- Jamaica. Woodes Rogers' bedroom January 25th, 1725.zip](https://github.com/PiratesAhoy/new-horizons/files/12641489/-.Player.-.Jamaica.Woodes.Rogers.bedroom.January.25th.1725.zip)

**Comment by Hammie** [comment]
Crash fixed by https://github.com/storm-devs/storm-engine/commit/f6d068dd1bca635a333047a38fcf317572d9cee8
