### ISSUE TITLE
Devlin Opera - My Life as a Waitress Quest is broken

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#132]
When you ask the barkeeper on Santo Domingo about Marcel Jauri, the dialogue cycles like normal and Gullie the Kid shows up in the tavern to prompt you to follow him outside. When you go outside the tavern, he's supposed to give you dialogue to follow him to a corner of town where you then follow him, but he does not spawn outside at all, and I checked every part of the town too, he just does not spawn anywhere and you cannot continue with the quest since he doesn't appear outside to prompt you what to do next once you leave the tavern. I will provide a save, just talk to the barkeeper about business to discuss, ask about Marcel Jauri, Gullie will talk to you in the Tavern, and then you'll see he will never meet you outside, breaking the quest. This is on the Latest Alpha 14 build. I cannot continue testing the questline until this is fixed.

Quest: `meet_kid_outside`

[-=Devlin Opera Test=- Hispaniola. Santo Domingo tavern May 24th, 1576.zip](https://github.com/PiratesAhoy/new-horizons/files/12668607/-.Devlin.Opera.Test.-.Hispaniola.Santo.Domingo.tavern.May.24th.1576.zip)

**Comment by Hammie** [comment]
Santo Domingo Town is simply missing the locators used in the quest script.
