### ISSUE TITLE
Player keeps stowing his weapon

### ISSUE THREAD

**Issue by Hammie** [PiratesAhoy/new-horizons#135]
> Not sure but there might be a bug in the storyline since the character keeps stowing his weapon every couple of seconds which makes it pretty much impossible to fight anybody
> 
> -- DH27

Version: 15.0.0-alpha.14

[-=Player=- Jamaica.zip](https://github.com/PiratesAhoy/new-horizons/files/12702978/-.Player.-.Jamaica.zip)

**Comment by Hammie** [comment]
There is an explicit timer that fires every 0.5 seconds forcing the player to stow his weapon, so this appears to be intentional

**Comment by DH2706** [comment]
[-=Player=- Jamaica. Rogers' storeroom January 29th, 1725.zip](https://github.com/PiratesAhoy/new-horizons/files/12706056/-.Player.-.Jamaica.Rogers.storeroom.January.29th.1725.zip)

The savefile in the cargo hold seems to be the closest to the arising of the bug that I can get. The savefile before does not hvae that bug and the savefile after the cargo hold has the bug

**Comment by Hammie** [comment]
Timer quest: `remove_planks_hold2`
