### ISSUE TITLE
Gold Bug storyline: Can't proceed from first shore to the second

### ISSUE THREAD

**Issue by DH2706** [PiratesAhoy/new-horizons#136]
After picking up the four dead birds, when I try to move to the second shore by jumping from the empty room in the shipwreck to the other side of the shipwreck, the character gets stuck and no menu can be opened anymore. 
[-=Player=- Bonaire. Sullivan shore October 15th, 1830.zip](https://github.com/PiratesAhoy/new-horizons/files/12706180/-.Player.-.Bonaire.Sullivan.shore.October.15th.1830.zip)

**Comment by Hammie** [comment]
I tried this starting a new game, and I got to the second shore without problems, so I'm assuming it is fixed in alpha 16
