### ISSUE TITLE
Freeplay storyline: When you die on Khael Roa, you just lie there dead and cannot do anything anymore

### ISSUE THREAD

**Issue by DH2706** [PiratesAhoy/new-horizons#139]
I died on Khael Roa to some natives and I am assuming that I should be resurrected because after the death movie, I regain my health fully. Only problem ist that the character keeps laying on the ground and nothing happens. if you press F1 it says you can't save or load until Sir Richard Dutton leaves. I am assuming that something is not working with the despawning of that character.
[-=Player=- Cozumel. Khael Roa jungles July 15th, 1682.zip](https://github.com/PiratesAhoy/new-horizons/files/12706671/-.Player.-.Cozumel.Khael.Roa.jungles.July.15th.1682.zip)

**Comment by Hammie** [comment]
You probably survived the attack, in which case it normally teleports you to the tavern. Problem is probably that that island does not have a tavern.
