### ISSUE TITLE
No longer any sound for selecting dialogue options or scrolling through them

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#144]
I'm playing Alpha 16 and I think the new interface sounds didn't quite translate to the dialogue menus, now when I select options in the dialogue menus, I cannot hear anything when I select an option or scroll through the options and there was a sound for selecting dialogue options and scrolling through them before, please correct.

**Comment by Hammie** [comment]
The dialog tick sound is apparently hard-coded in the engine
