### ISSUE TITLE
Saving game causes "incompatible Save" (Stormx)

### ISSUE THREAD

**Issue by SneakyMcSnakey** [PiratesAhoy/new-horizons#16]
Hi, just trying it out on FreePlay.
Every time I save it instantly goes to "Incompatible Save".
![bild](https://user-images.githubusercontent.com/89080047/212546234-e153750a-13fb-46c8-8494-00c42542618c.png)

**Comment by Hammie** [comment]
For some reason the game thinks saves are incompatible some of the time. Haven't found out why yet.

You can disable this line as a temporary workaround: https://github.com/PiratesAhoy/new-horizons/blob/stormx/PROGRAM/INTERFACE/save_load.c#L339 
```SetSelectable("LOAD_BUTTON", bFilePresent && !bCorrupted && !bIncompatible && !bThisSave);```
Just comment it out:
```// SetSelectable("LOAD_BUTTON", bFilePresent && !bCorrupted && !bIncompatible && !bThisSave);```

**Comment by Hammie** [comment]
I think this may have actually been caused as a side-effect of the dialog issue https://github.com/PiratesAhoy/new-horizons/issues/20

Have not seen this happen since I fixed that

**Comment by sergiogomes66** [comment]
Just to clarify, I'm Bartolomeu o Portuguese from the PA! Forum.
I played today for the first time the game and I can confirm the bug exists. I suppose the fix will be available in the next update.

**Comment by Hammie** [comment]
Was able to reproduce this on the latest version.

I'm now pretty confident it is being caused by a script caching bug. Deleting the cache results in a 50% chance of it being broken or fixed.

I recommend disabling the script cache in the `engine.ini` for now:
```
[script]
; Script caching mode, 0 = disable, 1 = check on load, 2 = check only at start
cache_mode = 0
```
