### ISSUE TITLE
Texture gone after capturing ship (Stormx)

### ISSUE THREAD

**Issue by SneakyMcSnakey** [PiratesAhoy/new-horizons#17]
Hello,
This happend when I captured a ship and exiting the "capture" screen.
Both mine and the captured ship lost textures.
![bild](https://user-images.githubusercontent.com/89080047/212560696-3486487a-4402-4b1d-8df7-081656a5b4d5.png)

**Comment by SneakyMcSnakey** [comment]
Reloading the save makes the texture come back.
This bug does not happen everytime you capture a ship.

**Comment by tommy61157** [comment]
Can confirm this happens for me too even on the latest alpha 8
