### ISSUE TITLE
Issues while attacking forts

### ISSUE THREAD

**Issue by Soyuz247** [PiratesAhoy/new-horizons#180]
Only front cannons work in capturing forts, broadsides does nothing.

Unless there are ships nearby, a heavy spike lag could be experienced when near forts. 

Unless there are ships nearby, attacking the fort doesn't work

There is a crash right after the capturing fort for myself dialog

**Comment by tommy61157** [comment]
Duplicate of #83

**Comment by tommy61157** [comment]
I'm going to close this as this is a duplicate issue and Hammie already has this marked for completion for the beta
