### ISSUE TITLE
CTD during Hoist the Colours (StormX)

### ISSUE THREAD

**Issue by SneakyMcSnakey** [PiratesAhoy/new-horizons#20]
Hello,
I get an instant CTD when trying to enter Grand Cayman Port (Where the guards stop you).
The bit after you switch from Guy to Jack.
I see the dialogue from the guards open for a split second before CTD.
[exceptions.log](https://github.com/PiratesAhoy/new-horizons/files/10428011/exceptions.log)
[mimalloc.log](https://github.com/PiratesAhoy/new-horizons/files/10428012/mimalloc.log)
[script_stack.log](https://github.com/PiratesAhoy/new-horizons/files/10428013/script_stack.log)
[system.log](https://github.com/PiratesAhoy/new-horizons/files/10428014/system.log)
[compile.log](https://github.com/PiratesAhoy/new-horizons/files/10428015/compile.log)
[error.log](https://github.com/PiratesAhoy/new-horizons/files/10428016/error.log)

**Comment by Hammie** [comment]
null-pointer exception in `LegacyDialog::DrawHeadModel`

https://github.com/storm-devs/storm-engine/blob/150c1a483a96d3bab36e099976555810a81493c0/src/libs/dialog/src/legacy_dialog.cpp#L560

Looks like someone does not have a head 😱
