### ISSUE TITLE
Impossible to reload on the worldmap

### ISSUE THREAD

**Issue by sergiogomes66** [PiratesAhoy/new-horizons#26]
Caught by a storm again but this time no enemy fleet next to me.
My ship was stuck and when I wanted to reload on the worldmap, I was always reloaded at sea.

**Comment by Hammie** [comment]
[-=Player=- Sea Reload Bug.zip](https://github.com/PiratesAhoy/new-horizons/files/11235750/-.Player.-.Sea.Reload.Bug.zip)
