### ISSUE TITLE
Incorrect starting skill points at game start

### ISSUE THREAD

**Issue by Hammie** [PiratesAhoy/new-horizons#34]
When starting a new game with manual skill assignment, you do not get 2 free skill points.

**Comment by tommy61157** [comment]
This also affects the classes not starting with a couple of levels and some predefined skill points like they should

**Comment by Hammie** [comment]
Related to #46

**Comment by Hammie** [comment]
[Ygramul](https://www.piratesahoy.net/members/ygramul.29060/):
> To the issue mentioned before, that the game doesn't start you off with the appropriate 2 skill points, this is fixed by editing the characters_init. :
Go for the line " ch.skill.freeskill = 0; " and set it from 0 to 2 (or whatever you like) 

https://www.piratesahoy.net/threads/beyond-new-horizons-alpha-release.34218/post-597973
