### ISSUE TITLE
Black screen when entering port

### ISSUE THREAD

**Issue by Hammie** [PiratesAhoy/new-horizons#35]
When entering the Tortuga or Santiago harbor, yet get a black screen.

Error log:
```
RUNTIME ERROR in <no debug information>(1): Cant create class: NPCharacter
```

Storyline: Freeplay
Version: 15.0.0-alpha.7

**Comment by tommy61157** [comment]
Yeah, this is a problem, as long as this is going on, can't get what I need to access the secret island to remove the coin curse and access the special ships to test for the Build Mod 15, may want to up the priority on this. At least for Tortuga.

**Comment by Hammie** [comment]
Problem was caused by invalid collision data in location flag pole models. Regenerating the collision data for the Santiago and Tortuga flag poles fixed the problem.
