### ISSUE TITLE
World Map ship speeds seem to be unusually slow

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#44]
World Map ship speeds seem to be unusually slow. This makes completing certain trade missions near impossible along with certain other missions in general that are timed.

**Comment by tommy61157** [comment]
Sorry, just to note, this is with the Alpha 7 build on the Tales of a Sea Hawk Storyline.

**Comment by Hammie** [comment]
The actual ship speed appears to be hardcoded in the engine. I've reduced the speed at which time passes, let's see if this makes it more manageable.

**Comment by tommy61157** [comment]
Yeah, that would be a good workaround, this would also be acceptable

**Comment by tommy61157** [comment]
Slow the time progression by another 20-25% from what it is set to in Alpha 8 and this should be just fine.

**Comment by tommy61157** [comment]
So, I think this will need a deeper dive, this is still a major issue and really causes issues in quests like Hornblower where you are given just enough food and rum to barely make it through the questline on some ship ventures. Doesn't make the quest unplayable or anything as you can easily get just enough money to buy more food and rum if you have to, though this shouldn't even have to be a concern in the Hornblower storyline if you're just going straight to the destination like I am.
