### ISSUE TITLE
Scrolling down dialogue enough when speaking to anyone in a house causes dialog options to disappear

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#45]
Scrolling down dialogue enough when speaking to anyone in a house causes dialog options to disappear. They reappear one by one as you scroll up. I can provide a screenshot upon request, but this should be fairly easy to replicate, seems to only affect the civilians in houses as far as I can tell so far.

**Comment by tommy61157** [comment]
Sorry, just to note, this is with the Alpha 7 build on the Tales of a Sea Hawk Storyline.

**Comment by Hammie** [comment]
Probably a bug in https://github.com/storm-devs/storm-engine/pull/482
