### ISSUE TITLE
Glitchy mouse on main menu screen

### ISSUE THREAD

**Issue by Hammie** [PiratesAhoy/new-horizons#5]
Mouse cursor behaves strangely on the main menu

**Comment by DavyJack** [comment]
[compile.log](https://github.com/PiratesAhoy/new-horizons/files/9174637/compile.log)
[error.log](https://github.com/PiratesAhoy/new-horizons/files/9174638/error.log)
[system.log](https://github.com/PiratesAhoy/new-horizons/files/9174639/system.log)
Same issues here.

**Comment by Hammie** [comment]
Finally figured it out. The cursor is actually still working, just drawn incorrectly.

It's the `Glows` element - which draws the sparkles on top of the logo - used in the main menu that is messing things up. It calls `DX9RENDER::DrawRects` whenever it wants to draw something, which does not correctly restore the world-matrix used by the menu system.
