### ISSUE TITLE
Sun Creates a square lighting effect

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#53]
Idk what exactly causes this, sometimes it happens, sometimes it doesn't. The screenshots I took should be able to speak for themselves though.

Build: Alpha 7
Storyline: Tales of a Sea Hawk

![Screenshot 2023-04-22 161509](https://user-images.githubusercontent.com/4907391/233808013-5d6ca321-2c18-4253-bcff-7772067518e4.png)
![Screenshot 2023-04-22 161534](https://user-images.githubusercontent.com/4907391/233808015-4adfb18c-526f-4f33-89ed-e2d54b6577ac.png)
![Screenshot 2023-04-22 161654](https://user-images.githubusercontent.com/4907391/233808018-5f8da99e-b06b-4061-adec-ccbf5de3fd53.png)

**Comment by Hammie** [comment]
![Beyond New Horizons 4_26_2023 11_48_23 AM](https://user-images.githubusercontent.com/1293169/234539518-0c024479-fa73-4eaa-b359-9b8059a626de.png)
