### ISSUE TITLE
Possible issue with Autorun notification text

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#64]
If you turn off auto run with the K key (By default), save and exit the game, then load the save. If you try enabling autorun again, it will say it has been turned off, when really, it has been turned back on. So, the state of the autorun functionality is being saved, just the notification text on the top left is not fully reflective of it sometimes. Doesn't seem to always be recreateable, would like to see if others could verify this is an issue in their game as well before we get too deep into this.

Build: Alpha 7
Storyline: Tales of a Sea Hawk

**Comment by Hammie** [comment]
I think for me it always broken/inverted
