### ISSUE TITLE
When confirming that you are done taking things from a ship you boarded, the game crashes

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#68]
When completed with boarding and you confirm you are good to go, the game crashes after you confirm you want to leave the boarding aftermath screen. I did discard some goods and transfer goods and crew over, I did not transfer any cannons over, there was still some leftover crew on the ship. I was in a Merchant Pinnace and they were in a light brig. They were marked as Pirates and I was flying british flags, this happened the first time I tried boarding in the build mod. Going to see if I can repeat this, don't really have a save I can provide though since you can never really run into the same save twice.

Build: Alpha 7
Storyline: Tales of a Sea Hawk

**Comment by tommy61157** [comment]
Tried again, boarded another kind of ship, this time no crash and everything transferred, but now apparently my ship has no texture? Weird... Going into map view and back to normal ship view fixes this though, not permanent, but something weird is going on with boarding.

![Screenshot 2023-04-23 154652](https://user-images.githubusercontent.com/4907391/233865439-5d5dd0eb-f896-49c3-87d4-71daeb923f74.png)

**Comment by tommy61157** [comment]
Now I can't seem to recreate this on a new save, I should note that this is happening on the same profile where I got the #67 Glitch. Cannot replicate yet on a new save.

**Comment by Hammie** [comment]
The missing textures is a known issue: #13 
Also happens when you go to deck view and back.

**Comment by tommy61157** [comment]
Crash dump from exactly this issue! Hope this helps!

[63dffd97-6998-44aa-967b-73e5ff2a15ce.zip](https://github.com/PiratesAhoy/new-horizons/files/11315602/63dffd97-6998-44aa-967b-73e5ff2a15ce.zip)

**Comment by tommy61157** [comment]
Later in the Save, there are times where I can go into the F2 menu without issue too which is weird, this will need to be further investigated at some point
