### ISSUE TITLE
English Officer does not play the hit animation to hit Nathaniel

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#70]
English Officer does not play the hit animation to hit Nathaniel when the british come to try and arrest Danielle in the Port Royale Tavern after coming back to Port Royale with Tobias and then going to the Tavern. Minor Bug, quest will still progress normally without the animation. Your character still makes the animation like they've been hit too.

Build: Alpha 7
Storyline: Tales of a Sea Hawk.

**Comment by Hammie** [comment]
Do you happen to have a savegame by any chance?

**Comment by tommy61157** [comment]
Here you go, just be sure to unzip first as always. Talk to the woman at the bar with the ponytails (Danielle) and just go through her dialog, The british soldier who doesn't play the animation will then start talking to you right after, just pay attention to what happens there and I think you'll get the gist of what's going on.

Note: This save was made using the Alpha 7 with the hotfix!

[-=Build Mod 15 Test 3=- Jamaica. Port Royale tavern October 22nd, 1750.zip](https://github.com/PiratesAhoy/new-horizons/files/11316107/-.Build.Mod.15.Test.3.-.Jamaica.Port.Royale.tavern.October.22nd.1750.zip)
