### ISSUE TITLE
Specific Crash when exiting character screen when ship is out at sea

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#79]
Sometimes when I have a ship out on the open sea and I go into the character menu and then hit the X on the top right to go back out to the sea view, the game will Crash. I have the crash log attached.

Build: Alpha 7 (Hotfix)
Storyline: Tales of a Sea Hawk

[b96b3781-1a8d-48d5-ab9f-3741c07e41eb.zip](https://github.com/PiratesAhoy/new-horizons/files/11315725/b96b3781-1a8d-48d5-ab9f-3741c07e41eb.zip)

**Comment by tommy61157** [comment]
I think this may be happening when I try to assign skill points or abilities at sea and then hit X. Here's a save to try that on and see if you get the crash as well, if I assign skill points and an ability, I get the crash:

[-=Build Mod 15 Test 2=- Open Sea October 5th, 1754.zip](https://github.com/PiratesAhoy/new-horizons/files/11315775/-.Build.Mod.15.Test.2.-.Open.Sea.October.5th.1754.zip)

**Comment by tommy61157** [comment]
So, I should note, the ability I kept trying to assign is shared experience, not sure if any other ability also causes the crash, that may need to be tested, but noticed also that now I had it crash once later on when exiting the relations screen after I assigned an ability later too when out on the open sea, here's the crash log from that:

[3d4b33d7-8c53-4fd8-a8a0-36707b63caac.zip](https://github.com/PiratesAhoy/new-horizons/files/11315828/3d4b33d7-8c53-4fd8-a8a0-36707b63caac.zip)

Not sure if this is tied to me assigning the ability, the open sea itself, or both, or if something else is going on under the hood, there is a save that seems to be affected above as stated previously if you try to assign the ability in the open sea and then exit, I would try the shared experience ability and then try some other abilities to further drill down on what may be going on. Hope this all helps!

**Comment by tommy61157** [comment]
Also, being at the special spot in the quest I am in that save doesn't seem to affect it since even once I leave that part of the quest later in the second crash, I still can get the crash.

**Comment by tommy61157** [comment]
Unfortunately now, I have a save which seems to crash when I go to sea and do anything in the "F2" Menu, here's the latest save where you can try it yourself and the latest crash log, this is somewhat impeding my testing ability, so hopefully we can get this fixed soon. Note using F2 Menu when on land doesn't seem to cause issues:

(It's tied to either the Shared experience ability, the sea, assigning abilities past a certain level, some other factor, or some combination of the above)

[-=Build Mod 15 Test 2=- Puerto Rico. San Juan shipyard October 26th, 1754.zip](https://github.com/PiratesAhoy/new-horizons/files/11315859/-.Build.Mod.15.Test.2.-.Puerto.Rico.San.Juan.shipyard.October.26th.1754.zip)

[fc56e0d3-b623-428a-8f8c-39b55348c639.zip](https://github.com/PiratesAhoy/new-horizons/files/11315863/fc56e0d3-b623-428a-8f8c-39b55348c639.zip)

**Comment by tommy61157** [comment]
Confirmed that this crash will not happen if I go to ship deck while out on the sea and then try to access the F2 menu, only crashes when I use the F2 Menu in the ship view.

**Comment by Hammie** [comment]
Crash happened in `Ship_CheckSituation`, probably caused by a corrupted attribute.

Did not manage to reproduce it from the save games though :(

**Comment by tommy61157** [comment]
This crash is on and off, will need to further investigate I suppose, definitely not something we want to happen with any sort of regularity though, so we'll definitely need to figure it out. Could it have anything to do with the fact that I'm running the game with locked perks disabled? Idk
