### ISSUE TITLE
Deck of Dauntless class 1st Rate is not spawning correctly

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#81]
I'll either be put at a black screen or a screen where I see only the sea, I think the ship is not loading in correctly, I cannot go to other parts of the ship either. Not sure if this affects other first rate ships, though a lot of them draw from the same deck file so the fix for the deck file for this ship may fix the others, but it clearly is expecting a deck which the game cannot get, will provide a save file with an affected ship. May need to check for any other ships affected by this. In ship view, this ship appears just fine though, but once you load the save, just try going onto the ship deck and you'll see what I mean.

Build: Alpha 7 (With Hotfix)
Storyline: Tales of a Sea Hawk

[-=Build Mod 15 Test 2=- Open Sea November 21st, 1754 1.zip](https://github.com/PiratesAhoy/new-horizons/files/11315975/-.Build.Mod.15.Test.2.-.Open.Sea.November.21st.1754.1.zip)

Eh, what the heck, an interesting screenshot as well:

![Screenshot 2023-04-24 214311](https://user-images.githubusercontent.com/4907391/234161716-9dafe35e-d1f0-4aa2-ba27-e09802c8c136.png)

**Comment by Hammie** [comment]
Issues also happens for several ships you can get from Vanderdecken:
> SneakyMcSnakey: On a sidenote, are some ship decks missing?
Trying out all the big ships at Vanderdeckens and it's just a black screen with the rain visable.

From `system.log`:
```
[2023-09-09 20:08:26.885] [system] [error] Failed to ReadFile: ios_base::failbit set: iostream stream error
[2023-09-09 20:08:26.886] [system] [info] resource\models\locations\decks\udeck2\udeck_ld.gm: ios_base::failbit set: iostream stream error```

**Comment by tommy61157** [comment]
This is still not fixed in Alpha 13, I will post a save here with the same affected ship

[-=Free Play Testing=- Open Sea July 2nd, 1682.zip](https://github.com/PiratesAhoy/new-horizons/files/12572400/-.Free.Play.Testing.-.Open.Sea.July.2nd.1682.zip)

**Comment by tommy61157** [comment]
Wait, I'm an idiot, you literally just fixed this, won't be in the latest build, so sorry, I'll reclose
