### ISSUE TITLE
Dauntless class 1st Rate sail issues

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#82]
So, just had this happen:

![Screenshot 2023-04-24 215142](https://user-images.githubusercontent.com/4907391/234162840-7c895b40-8b53-43c1-b4fd-b7d99fdf0021.png)

I'll provide the save file, this is the only ship this seems to have happened with. Do not know if other ships of the same class are affected. Potentially related to #81 ??? Maybe not, but just wanted to bring that up as well.

Build: Alpha 7 (With Hotfix)
Storyline: Tales of a Sea Hawk

[-=Build Mod 15 Test 2=- Open Sea November 30th, 1754.zip](https://github.com/PiratesAhoy/new-horizons/files/11316049/-.Build.Mod.15.Test.2.-.Open.Sea.November.30th.1754.zip)

**Comment by Hammie** [comment]
I've seen it happen randomly to other ships as well.

**Comment by tommy61157** [comment]
So far, this is the only ship I have witnessed this with, but I will report if I see this happen to others as well

**Comment by SneakyMcSnakey** [comment]
Can confirm this still happens.
I have had it happen on the 2 Dauntless Class ships and the Victory Class from Vanderdecken.
Seems to be due to the triangular sails at the front.
I've also seen it on some smaller ships.
