### ISSUE TITLE
Forts cannot be hit during ship Combat

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#83]
I was specifically trying to hit bridgetown fort, and I cannot hit the fort and deal damage to the canons, it keeps looking like the cannonballs go through the fort hitting the land behind it and never even hitting the fort to begin with. I am testing mainly with Bridgetown Fort in the Tales of the Sea Hawk Storyline when you have to attack it, but I tried attacking other forts as well including the other fort on the island and it seems to be having the same effect.

Sadly, I cannot complete the Tales of a Sea Hawk questline until this is fixed. The fort capture is simply not possible. Please treat with urgency. Seems to affect all forts.

Build: Alpha 7 (With hotfix)
Storyline: Tales of a Seahawk

**Comment by tommy61157** [comment]
Unfortunately in Alpha 9, this was not fixed, it appears to still be going through the fort itself and not disabling any cannons or even hitting the fort, it hits the land behind the fort still.

**Comment by tommy61157** [comment]
Confirmed this is the case with a new or an old save

**Comment by Hammie** [comment]
Are you using manual aiming?

**Comment by tommy61157** [comment]
No, and I have tried on new and old saves at Speightstown, Bridgetown, and Charlestown. I can test other forts if you would like.

**Comment by tommy61157** [comment]
[logs.zip](https://github.com/PiratesAhoy/new-horizons/files/11411668/logs.zip)

Here are my logs, it is either constantly making me aim above the cannons on the fort or the cannonballs are going through them, can't really tell, but it keeps hitting the land behind the fort whether I get close, far, mid-range, doesn't seem to matter. I know you had said you cannot reproduce, but I am still having issues here and I hope these logs can tell you something even if it's just that my installation is messed up in some way. All I did here in these logs was load my save near the fort then attack the fort for a bit then quit the game.

**Comment by SneakyMcSnakey** [comment]
I tried to battle the fort at Philipsburg (Saint Martin) and the shots are all going slightly above the fort.
Using manual aiming seems to only hit the beach infront.

**Comment by Hammie** [comment]
It seems the fort is being hit, but the particle effects are missing

**Comment by tommy61157** [comment]
In the latest Alpha 13 build, I can confirm that is indeed what is going on, just need the smoke effects added and it should be good, I think my last build was somewhat corrupted which was causing issues, once the smoke effects are back, feel free to close this issue

**Comment by tommy61157** [comment]
Okay, I think I discovered the issue, when using a first rate ship with Vanderdecken's Custom Cannons that go way beyond 32 caliber, for some reason, it always wants to overfire, this likely won't come up in normal gameplay, but should still be looked into to make sure that the few who do achieve this aren't suddenly too OP to conquer forts, lol

**Comment by tommy61157** [comment]
The issue specifically seems to be with the highest caliber cannonrade that Vanderdecken sells, Cannons up to that highest tier and all the long guns including the 42 pound long gun all seem to work just fine, we could leave that in as a way to nerf the highest power tri-cannon in the game, or figure out what is going on with that highest upgrade. Otherwise, yeah, just need the particle effects back for when cannons are destroyed on the fort

**Comment by tommy61157** [comment]
Here's a save and some logs for a fort I was having a really hard time capturing which should be a cakewalk on the free play storyline with the long guns that had worked earlier for other forts, not sure what is going on, but this clearly is not fully fixed, also, eventually, the cannon smoke animations were not loading and there was a point or two where the audio reverbed really badly if I got in a situation where I fired both broadsides, both unrelated, but you may want to take a full look through this example, make sure there's nothing wrong here:

[-=Free Play Testing=- Open Sea October 15th, 1682.zip](https://github.com/PiratesAhoy/new-horizons/files/12591697/-.Free.Play.Testing.-.Open.Sea.October.15th.1682.zip)

[Logs.zip](https://github.com/PiratesAhoy/new-horizons/files/12591699/Logs.zip)

**Comment by tommy61157** [comment]
Due to this being an issue only with higher tier Cannons/Ships, I'm going to remove the Storyline Breaking tag as there are still very much ways around this that I have found for now, though this should still be high priority.

**Comment by Hammie** [comment]
I tweak the cannon handling code and did some testing, and I think it should be fixed in the next update
