### ISSUE TITLE
When talking to the Helmsman to go to sea, Game Crashes

### ISSUE THREAD

**Issue by tommy61157** [PiratesAhoy/new-horizons#91]
In the beginning of the Horatio Hornblower questline, you need to speak to the Helmsman who you give directions to, and once you get through his dialogue, it's supposed to take you to the Sea View on the HMS Justinian, but instead the game crashes. Questline cannot continue.

Build: Alpha 8
Storyline: Horatio Hornblower

Crash logs and Save zipped together below. When loading the save, talk to the helmsman in front of you and exhaust his dialogue fully then wait a second, game will then crash.

[-=Player=- Antigua. Ship deck June 18th, 1798.zip](https://github.com/PiratesAhoy/new-horizons/files/11327649/-.Player.-.Antigua.Ship.deck.June.18th.1798.zip)

**Comment by Hammie** [comment]
Could not reproduce, but the crashes were a result of a nullptr-exception during Fader initialization, which I have fixed.

**Comment by tommy61157** [comment]
Good news, on running the game again today, the crash is no longer happening! I know there is a deeper engine bug that can be fixed, but this is no longer breaking the storyline, so I can at least continue testing

**Comment by tommy61157** [comment]
On further examination, reapplying the storyline breaking since this technically does break the storyline when it happens, even if it randomly works
